import type { TrendingDish } from "./types";

export const TRENDING_DISHES: TrendingDish[] = [
  {
    id: "creator-wanggang-huiguorou",
    name: "家常版回锅肉",
    source: "B站",
    creator: "美食作家王刚R",
    creatorNote: "硬核中餐教程型 UP，适合想把一道家常菜做扎实的时候看。",
    taste: "辣",
    difficulty: "中等",
    cookTime: 28,
    ingredients: [
      { name: "五花肉", amount: "300g" },
      { name: "青蒜", amount: "4根" },
      { name: "郫县豆瓣酱", amount: "1勺" },
      { name: "甜面酱", amount: "半勺" },
    ],
    steps: ["五花肉冷水下锅煮至断生，放凉切薄片。", "小火煸出肉片油脂，加入豆瓣酱炒出红油。", "下青蒜和甜面酱快速翻炒，补少许生抽出锅。"],
    reason: "王刚系菜谱更偏基础功和锅气，回锅肉是适合练火候的下饭硬菜。",
    tags: ["B站UP主", "川味", "下饭菜"],
    searchKeyword: "美食作家王刚R 回锅肉",
  },
  {
    id: "creator-laofangu-yuxiangrousi",
    name: "鱼香肉丝",
    source: "B站",
    creator: "老饭骨",
    creatorNote: "老师傅讲细节的中餐频道，适合想把调味比例做稳定的人。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 26,
    ingredients: [
      { name: "里脊肉", amount: "250g" },
      { name: "木耳", amount: "1把" },
      { name: "胡萝卜", amount: "半根" },
      { name: "泡椒", amount: "2勺" },
    ],
    steps: ["里脊切丝上浆，配菜切丝。", "调鱼香汁：醋、糖、生抽、淀粉和清水混合。", "肉丝滑散后炒香泡椒，加入配菜和鱼香汁收浓。"],
    reason: "鱼香味最怕比例飘，老饭骨类教程适合对照学习调味逻辑。",
    tags: ["B站UP主", "经典家常", "调味练习"],
    searchKeyword: "老饭骨 鱼香肉丝",
  },
  {
    id: "creator-manshiman-yu-tomato-beef",
    name: "番茄牛腩",
    source: "B站",
    creator: "曼食慢语",
    creatorNote: "步骤清楚、画面舒服，适合周末备餐和慢炖菜。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 70,
    ingredients: [
      { name: "牛腩", amount: "500g" },
      { name: "番茄", amount: "4个" },
      { name: "土豆", amount: "1个" },
      { name: "洋葱", amount: "半个" },
    ],
    steps: ["牛腩焯水，番茄去皮切块。", "洋葱和番茄炒出浓汁，加入牛腩和热水炖煮。", "最后加入土豆炖软，盐和黑胡椒调味。"],
    reason: "适合一次多做，第二天拌饭或带饭都很稳。",
    tags: ["B站UP主", "炖菜", "备餐"],
    searchKeyword: "曼食慢语 番茄牛腩",
  },
  {
    id: "creator-mianyang-teriyaki-chicken",
    name: "照烧鸡腿饭",
    source: "B站",
    creator: "绵羊料理",
    creatorNote: "创意和实用感兼具，适合想把普通食材做得更有期待感。",
    taste: "甜",
    difficulty: "简单",
    cookTime: 24,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "米饭", amount: "2碗" },
      { name: "生抽", amount: "2勺" },
      { name: "蜂蜜", amount: "1勺" },
    ],
    steps: ["鸡腿去骨，用少许盐和黑胡椒腌制。", "鸡皮面先煎出油脂，翻面煎熟。", "倒入照烧汁收浓，切块盖在米饭上。"],
    reason: "鸡腿饭是视频平台常青题材，食材好买、成品反馈强。",
    tags: ["B站UP主", "盖饭", "一人食"],
    searchKeyword: "绵羊料理 照烧鸡腿饭",
  },
  {
    id: "creator-daoyueshe-market-stir-fry",
    name: "菜市场小炒肉",
    source: "B站",
    creator: "盗月社食遇记",
    creatorNote: "偏烟火气和市井灵感，适合不知道买什么时去找菜市场思路。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 20,
    ingredients: [
      { name: "梅花肉", amount: "250g" },
      { name: "螺丝椒", amount: "4个" },
      { name: "蒜", amount: "3瓣" },
      { name: "豆豉", amount: "1勺" },
    ],
    steps: ["肉切薄片，螺丝椒拍裂切段。", "热锅煸香肉片和蒜，加入豆豉。", "下辣椒大火炒出虎皮感，用生抽和盐调味。"],
    reason: "这类内容更像“今天去市场看到什么就做什么”，适合解决选择困难。",
    tags: ["B站UP主", "菜市场", "快手下饭"],
    searchKeyword: "盗月社食遇记 菜市场 小炒肉",
  },
  {
    id: "creator-gaoyuyu-sprite-noodle",
    name: "雪碧拌面",
    source: "小红书",
    creator: "高芋芋",
    creatorNote: "小红书爆款美食博主路线，适合想要低门槛、强记忆点的快手菜。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 15,
    ingredients: [
      { name: "面条", amount: "2份" },
      { name: "黄瓜", amount: "半根" },
      { name: "雪碧", amount: "3勺" },
      { name: "芝麻酱", amount: "1勺" },
    ],
    steps: ["面条煮熟过凉水，黄瓜切丝。", "用芝麻酱、生抽、醋、辣椒油和少量雪碧调汁。", "面条沥干后拌匀，按口味补蒜末和香菜。"],
    reason: "适合没胃口或不想开大火的时候，平台传播感很强。",
    tags: ["小红书博主", "快手面", "爆款感"],
    searchKeyword: "高芋芋 雪碧拌面",
  },
  {
    id: "creator-xiaoyugugu-cheese-chicken",
    name: "芝士鸡腿",
    source: "小红书",
    creator: "小宇菇菇",
    creatorNote: "高颜值还原和治愈系美食内容，适合周末做一顿有仪式感的。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 35,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "芝士片", amount: "2片" },
      { name: "面包糠", amount: "适量" },
      { name: "鸡蛋", amount: "1个" },
    ],
    steps: ["鸡腿去骨展开，盐和黑胡椒腌制。", "夹入芝士后裹蛋液和面包糠。", "空气炸锅或烤箱烤至表面金黄。"],
    reason: "比普通鸡腿更有新鲜感，适合想吃点开心的晚餐。",
    tags: ["小红书博主", "空气炸锅", "高颜值"],
    searchKeyword: "小宇菇菇 芝士鸡腿",
  },
  {
    id: "creator-pupujiji-bento",
    name: "照烧鸡腿便当",
    source: "小红书",
    creator: "噗噗叽叽",
    creatorNote: "便当和家常菜氛围强，适合把晚餐顺手变成第二天午餐。",
    taste: "甜",
    difficulty: "简单",
    cookTime: 28,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "西兰花", amount: "半颗" },
      { name: "胡萝卜", amount: "半根" },
      { name: "米饭", amount: "2碗" },
    ],
    steps: ["鸡腿去骨煎熟，倒入照烧汁收汁。", "西兰花和胡萝卜焯水调味。", "米饭装盒，铺上鸡腿和配菜。"],
    reason: "适合工作日，做一顿能解决晚餐和带饭。",
    tags: ["小红书博主", "便当", "带饭"],
    searchKeyword: "噗噗叽叽 照烧鸡腿便当",
  },
  {
    id: "creator-xiashu-tofu",
    name: "葱烧豆腐",
    source: "小红书",
    creator: "夏叔厨房",
    creatorNote: "主厨经验型内容，适合想学接地气但有章法的中餐。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 18,
    ingredients: [
      { name: "老豆腐", amount: "1块" },
      { name: "大葱", amount: "1根" },
      { name: "生抽", amount: "2勺" },
      { name: "蚝油", amount: "1勺" },
    ],
    steps: ["豆腐切厚片煎到两面金黄。", "大葱煸香，加入生抽、蚝油和少许水。", "放回豆腐小火烧入味，收汁出锅。"],
    reason: "便宜、下饭、蛋白质够，是一周菜单里很好补位的素菜。",
    tags: ["小红书博主", "豆腐", "省钱菜"],
    searchKeyword: "夏叔厨房 葱烧豆腐",
  },
  {
    id: "creator-panlaolao-chicken-potato",
    name: "土豆烧鸡",
    source: "小红书",
    creator: "潘姥姥",
    creatorNote: "乡间家常和治愈感强，适合想吃朴素热乎炖菜的时候。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 45,
    ingredients: [
      { name: "鸡块", amount: "500g" },
      { name: "土豆", amount: "2个" },
      { name: "姜", amount: "4片" },
      { name: "八角", amount: "1个" },
    ],
    steps: ["鸡块焯水，土豆切滚刀块。", "炒香姜片和鸡块，加入生抽、老抽和热水。", "炖至鸡肉入味后下土豆，收浓汤汁。"],
    reason: "热乎、有汤汁、很适合米饭，是不容易踩雷的家常炖菜。",
    tags: ["小红书博主", "炖菜", "家常"],
    searchKeyword: "潘姥姥 土豆烧鸡",
  },
  {
    id: "creator-wanggang-kungpao-chicken",
    name: "宫保鸡丁",
    source: "B站",
    creator: "美食作家王刚R",
    creatorNote: "硬核中餐教程型 UP，适合想把一道家常菜做扎实的时候看。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 24,
    ingredients: [
      { name: "鸡腿肉", amount: "300g" },
      { name: "花生米", amount: "1把" },
      { name: "干辣椒", amount: "6个" },
      { name: "大葱", amount: "1根" },
    ],
    steps: ["鸡腿肉切丁上浆，调好糖醋宫保汁。", "热锅滑散鸡丁，炒香干辣椒和葱段。", "倒入鸡丁、花生米和料汁，大火翻匀收亮。"],
    reason: "同样是王刚路线，但比回锅肉更考验调汁，适合想练经典川菜的时候。",
    tags: ["B站UP主", "川菜", "鸡腿肉"],
    searchKeyword: "美食作家王刚R 宫保鸡丁",
  },
  {
    id: "creator-laofangu-braised-pork",
    name: "红烧肉",
    source: "B站",
    creator: "老饭骨",
    creatorNote: "老师傅讲细节的中餐频道，适合想把调味比例做稳定的人。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 65,
    ingredients: [
      { name: "五花肉", amount: "500g" },
      { name: "冰糖", amount: "1小把" },
      { name: "姜", amount: "5片" },
      { name: "生抽", amount: "2勺" },
    ],
    steps: ["五花肉切块焯水，沥干备用。", "小火炒糖色，下肉块翻匀。", "加热水和调味料慢炖，最后大火收汁。"],
    reason: "适合周末慢慢做的一道菜，喜欢老饭骨后会更多推荐这类传统中餐硬菜。",
    tags: ["B站UP主", "硬菜", "周末菜"],
    searchKeyword: "老饭骨 红烧肉",
  },
  {
    id: "creator-manshiman-curry-chicken",
    name: "日式咖喱鸡饭",
    source: "B站",
    creator: "曼食慢语",
    creatorNote: "步骤清楚、画面舒服，适合周末备餐和慢炖菜。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 35,
    ingredients: [
      { name: "鸡腿肉", amount: "300g" },
      { name: "土豆", amount: "1个" },
      { name: "胡萝卜", amount: "1根" },
      { name: "咖喱块", amount: "2块" },
    ],
    steps: ["鸡腿肉、土豆和胡萝卜切块。", "鸡肉煎香后加入蔬菜翻炒。", "加水煮软，放入咖喱块煮到浓稠。"],
    reason: "一锅解决主菜和拌饭，适合做成两顿饭。",
    tags: ["B站UP主", "盖饭", "备餐"],
    searchKeyword: "曼食慢语 日式咖喱鸡饭",
  },
  {
    id: "creator-mianyang-garlic-shrimp",
    name: "蒜香黄油虾",
    source: "B站",
    creator: "绵羊料理",
    creatorNote: "创意和实用感兼具，适合想把普通食材做得更有期待感。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 18,
    ingredients: [
      { name: "虾", amount: "300g" },
      { name: "蒜", amount: "1头" },
      { name: "黄油", amount: "15g" },
      { name: "黑胡椒", amount: "适量" },
    ],
    steps: ["虾开背去虾线，蒜切末。", "黄油融化后炒香蒜末。", "下虾煎熟，黑胡椒和盐调味。"],
    reason: "步骤短但成品有餐厅感，适合想换口味时刷新出来。",
    tags: ["B站UP主", "快手", "海鲜"],
    searchKeyword: "绵羊料理 蒜香黄油虾",
  },
  {
    id: "creator-gaoyuyu-sour-hot-mix",
    name: "酸辣凉拌宽粉",
    source: "小红书",
    creator: "高芋芋",
    creatorNote: "小红书爆款美食博主路线，适合想要低门槛、强记忆点的快手菜。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 16,
    ingredients: [
      { name: "宽粉", amount: "1把" },
      { name: "黄瓜", amount: "半根" },
      { name: "花生碎", amount: "1勺" },
      { name: "辣椒油", amount: "1勺" },
    ],
    steps: ["宽粉煮熟过凉水，黄瓜切丝。", "生抽、醋、辣椒油、蒜末调成酸辣汁。", "把宽粉和配菜拌匀，撒花生碎。"],
    reason: "和雪碧拌面同属低门槛爆款路线，适合不想认真开火的晚上。",
    tags: ["小红书博主", "凉拌", "快手"],
    searchKeyword: "高芋芋 酸辣宽粉",
  },
  {
    id: "creator-pupujiji-omelet-rice",
    name: "蛋包饭",
    source: "小红书",
    creator: "噗噗叽叽",
    creatorNote: "便当和家常菜氛围强，适合把晚餐顺手变成第二天午餐。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 25,
    ingredients: [
      { name: "米饭", amount: "2碗" },
      { name: "鸡蛋", amount: "3个" },
      { name: "番茄酱", amount: "2勺" },
      { name: "火腿", amount: "1根" },
    ],
    steps: ["米饭加火腿和番茄酱炒匀。", "鸡蛋打散，小火摊成蛋皮。", "蛋皮包住炒饭，表面挤番茄酱。"],
    reason: "视觉反馈强，适合想做一顿轻松但不敷衍的晚餐。",
    tags: ["小红书博主", "便当", "米饭"],
    searchKeyword: "噗噗叽叽 蛋包饭",
  },
  {
    id: "creator-xiashu-eggplant",
    name: "酱烧茄子",
    source: "小红书",
    creator: "夏叔厨房",
    creatorNote: "主厨经验型内容，适合想学接地气但有章法的中餐。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 22,
    ingredients: [
      { name: "茄子", amount: "2根" },
      { name: "蒜", amount: "4瓣" },
      { name: "黄豆酱", amount: "1勺" },
      { name: "青椒", amount: "1个" },
    ],
    steps: ["茄子切条，用少许盐抓一下出水。", "锅中煎软茄子，炒香蒜末和黄豆酱。", "加入青椒和茄子翻匀，少量水焖入味。"],
    reason: "素菜也能很下饭，适合喜欢夏叔厨房后补充传统家常菜。",
    tags: ["小红书博主", "素菜", "下饭"],
    searchKeyword: "夏叔厨房 酱烧茄子",
  },
  {
    id: "creator-panlaolao-ribs-corn",
    name: "玉米排骨汤",
    source: "小红书",
    creator: "潘姥姥",
    creatorNote: "乡间家常和治愈感强，适合想吃朴素热乎炖菜的时候。",
    taste: "清淡",
    difficulty: "简单",
    cookTime: 55,
    ingredients: [
      { name: "排骨", amount: "500g" },
      { name: "玉米", amount: "1根" },
      { name: "胡萝卜", amount: "1根" },
      { name: "姜", amount: "4片" },
    ],
    steps: ["排骨焯水洗净。", "排骨、姜片和清水先炖35分钟。", "加入玉米和胡萝卜继续炖，最后加盐。"],
    reason: "喜欢潘姥姥后，更适合推荐这种热乎、朴素、家常的汤菜。",
    tags: ["小红书博主", "汤菜", "清淡"],
    searchKeyword: "潘姥姥 玉米排骨汤",
  },
];

interface ExtraTrendingDish extends Omit<TrendingDish, "ingredients" | "searchKeyword"> {
  ingredients: Array<[string, string]>;
}

function extraDish(dish: ExtraTrendingDish): TrendingDish {
  return {
    ...dish,
    ingredients: dish.ingredients.map(([name, amount]) => ({ name, amount })),
    searchKeyword: `${dish.creator} ${dish.name}`,
  };
}

TRENDING_DISHES.push(
  extraDish({
    id: "creator-rishiji-cola-wings",
    name: "可乐鸡翅",
    source: "B站",
    creator: "日食记",
    creatorNote: "生活感强的家常料理路线，适合想轻松做一顿又不想太随便的时候。",
    taste: "甜",
    difficulty: "简单",
    cookTime: 30,
    ingredients: [["鸡翅", "10只"], ["可乐", "半罐"], ["姜", "4片"]],
    steps: ["鸡翅划刀焯水。", "小火煎至两面微黄，加入姜片。", "倒入可乐和生抽焖煮，收汁出锅。"],
    reason: "食材少、容错高，是工作日晚餐里很稳的一道。",
    tags: ["家常", "鸡翅", "新手友好"],
  }),
  extraDish({
    id: "creator-rishiji-beef-rice",
    name: "日式肥牛饭",
    source: "B站",
    creator: "日食记",
    creatorNote: "生活感强的家常料理路线，适合想轻松做一顿又不想太随便的时候。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 20,
    ingredients: [["肥牛卷", "250g"], ["洋葱", "半个"], ["米饭", "2碗"]],
    steps: ["洋葱切丝炒软。", "加入肥牛卷和调好的酱汁。", "煮到肥牛变色，盖在米饭上。"],
    reason: "一锅就能解决主菜和主食，适合下班后快速开饭。",
    tags: ["盖饭", "快手", "一人食"],
  }),
  extraDish({
    id: "creator-xiaogao-chicken-rice",
    name: "香菇鸡肉焖饭",
    source: "B站",
    creator: "小高姐的 Magic Ingredients",
    creatorNote: "步骤讲解细致，适合愿意照着做、把基础动作慢慢练熟的人。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 45,
    ingredients: [["鸡腿肉", "300g"], ["香菇", "6朵"], ["大米", "2杯"]],
    steps: ["鸡腿切块腌制，香菇切片。", "鸡肉和香菇炒香后铺在米上。", "按正常水量焖饭，熟后翻匀。"],
    reason: "一个电饭锅就能完成，适合做成第二天的便当。",
    tags: ["焖饭", "电饭锅", "带饭"],
  }),
  extraDish({
    id: "creator-xiaogao-beef-noodle",
    name: "红烧牛肉面",
    source: "B站",
    creator: "小高姐的 Magic Ingredients",
    creatorNote: "步骤讲解细致，适合愿意照着做、把基础动作慢慢练熟的人。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 80,
    ingredients: [["牛腩", "500g"], ["面条", "2份"], ["番茄", "2个"]],
    steps: ["牛腩焯水切块。", "炒香番茄和香料，加水慢炖牛腩。", "面条煮熟后浇上牛肉汤。"],
    reason: "适合周末做一锅，剩下的汤第二天还能继续吃。",
    tags: ["面食", "周末菜", "慢炖"],
  }),
  extraDish({
    id: "creator-dianxixiaoge-pot-chicken",
    name: "菌菇汽锅鸡",
    source: "B站",
    creator: "滇西小哥",
    creatorNote: "云南风味和自然食材路线，适合想让一周菜单多一点地方风味。",
    taste: "鲜",
    difficulty: "中等",
    cookTime: 75,
    ingredients: [["鸡块", "500g"], ["菌菇", "200g"], ["姜", "5片"]],
    steps: ["鸡块焯水洗净。", "鸡块、菌菇和姜片放入蒸锅。", "隔水慢蒸至汤汁清亮，最后加盐。"],
    reason: "清淡但不单薄，适合周末想喝热汤的时候。",
    tags: ["云南风味", "汤菜", "菌菇"],
  }),
  extraDish({
    id: "creator-dianxixiaoge-sour-fish",
    name: "酸汤鱼片",
    source: "B站",
    creator: "滇西小哥",
    creatorNote: "云南风味和自然食材路线，适合想让一周菜单多一点地方风味。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 35,
    ingredients: [["鱼片", "350g"], ["番茄", "3个"], ["金针菇", "1把"]],
    steps: ["鱼片用盐和淀粉抓匀。", "番茄炒出汁后加水煮成酸汤。", "加入金针菇和鱼片，煮熟调味。"],
    reason: "开胃、带汤，适合吃腻了常规炒菜时换口味。",
    tags: ["酸汤", "鱼片", "地方菜"],
  }),
  extraDish({
    id: "creator-mashizhuang-pasta",
    name: "黑椒牛肉意面",
    source: "B站",
    creator: "马壮实Hera",
    creatorNote: "偏实用西餐和家庭复刻，适合想在家做一点不同口味的人。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 25,
    ingredients: [["意面", "200g"], ["牛肉", "200g"], ["彩椒", "1个"]],
    steps: ["意面煮熟备用。", "牛肉切条快炒，加入彩椒。", "倒入黑椒汁和意面翻匀。"],
    reason: "比普通炒面更有新鲜感，但操作仍然很快。",
    tags: ["意面", "西餐", "快手"],
  }),
  extraDish({
    id: "creator-mashizhuang-salmon",
    name: "香煎三文鱼配蔬菜",
    source: "B站",
    creator: "马壮实Hera",
    creatorNote: "偏实用西餐和家庭复刻，适合想在家做一点不同口味的人。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 22,
    ingredients: [["三文鱼", "2块"], ["芦笋", "1把"], ["柠檬", "半个"]],
    steps: ["三文鱼擦干后加盐和黑胡椒。", "鱼皮面先煎脆，再翻面煎熟。", "配上煎蔬菜和柠檬汁。"],
    reason: "想吃清爽一点时很合适，也能把周菜单从重口味里拉回来。",
    tags: ["轻食", "海鲜", "高蛋白"],
  }),
  extraDish({
    id: "creator-lanfan-cabbage-pot",
    name: "白菜豆腐煲",
    source: "抖音",
    creator: "懒饭",
    creatorNote: "快手家常和一锅菜路线，适合没有精力洗很多锅的工作日。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 25,
    ingredients: [["白菜", "半颗"], ["豆腐", "1块"], ["粉丝", "1把"]],
    steps: ["白菜切块，豆腐煎至两面金黄。", "锅中铺白菜、豆腐和泡软的粉丝。", "加入高汤焖煮，最后调味。"],
    reason: "便宜、热乎、洗锅少，是天气转凉时很实用的晚餐。",
    tags: ["一锅菜", "豆腐", "省事"],
  }),
  extraDish({
    id: "creator-lanfan-tomato-rice",
    name: "番茄腊肠焖饭",
    source: "抖音",
    creator: "懒饭",
    creatorNote: "快手家常和一锅菜路线，适合没有精力洗很多锅的工作日。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 40,
    ingredients: [["腊肠", "2根"], ["番茄", "2个"], ["大米", "2杯"]],
    steps: ["腊肠切片，番茄切块。", "把食材铺在淘洗好的米上。", "电饭锅正常煮饭，熟后拌匀。"],
    reason: "备料很短，交给电饭锅后就能去做别的事。",
    tags: ["电饭锅", "焖饭", "省事"],
  }),
  extraDish({
    id: "creator-mastersdish-shrimp-ball",
    name: "宫保虾球",
    source: "B站",
    creator: "大师的菜",
    creatorNote: "偏经典菜和技法讲解，适合想把家常菜做得更像馆子味。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 28,
    ingredients: [["虾仁", "300g"], ["花生米", "1把"], ["干辣椒", "6个"]],
    steps: ["虾仁开背上浆。", "炒香干辣椒和葱段，加入虾仁。", "倒入宫保汁，撒花生米收亮。"],
    reason: "比宫保鸡丁更轻盈，适合周末练一道有反馈感的菜。",
    tags: ["经典菜", "海鲜", "调味练习"],
  }),
  extraDish({
    id: "creator-mastersdish-jingjiang-pork",
    name: "京酱肉丝",
    source: "B站",
    creator: "大师的菜",
    creatorNote: "偏经典菜和技法讲解，适合想把家常菜做得更像馆子味。",
    taste: "甜",
    difficulty: "中等",
    cookTime: 26,
    ingredients: [["里脊肉", "300g"], ["甜面酱", "2勺"], ["大葱", "1根"]],
    steps: ["里脊切丝上浆，大葱切细丝。", "肉丝滑熟盛出。", "甜面酱炒香后倒回肉丝，卷豆皮食用。"],
    reason: "食材常见但成品很有仪式感，适合想换一换桌面气氛。",
    tags: ["经典菜", "肉丝", "聚餐"],
  }),
  extraDish({
    id: "creator-amanda-clam-pasta",
    name: "蒜香蛤蜊意面",
    source: "B站",
    creator: "Amanda的小厨房",
    creatorNote: "家常西餐和烘焙路线，适合偶尔换掉米饭、给晚餐加一点变化。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 25,
    ingredients: [["意面", "200g"], ["蛤蜊", "400g"], ["蒜", "5瓣"]],
    steps: ["蛤蜊吐沙，意面煮熟。", "橄榄油炒香蒜末，加入蛤蜊焖至开口。", "倒入意面翻匀，撒黑胡椒。"],
    reason: "做法不难，但端上桌会比普通炒面更有新鲜感。",
    tags: ["意面", "海鲜", "换口味"],
  }),
  extraDish({
    id: "creator-amanda-roast-chicken",
    name: "香草烤鸡腿",
    source: "B站",
    creator: "Amanda的小厨房",
    creatorNote: "家常西餐和烘焙路线，适合偶尔换掉米饭、给晚餐加一点变化。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 45,
    ingredients: [["鸡腿", "4只"], ["土豆", "2个"], ["迷迭香", "适量"]],
    steps: ["鸡腿和土豆加盐、黑胡椒、香草腌制。", "平铺烤盘，淋少许油。", "烤至鸡皮金黄、土豆软糯。"],
    reason: "烤箱接管大部分工作，很适合周末一次做多一点。",
    tags: ["烤箱", "鸡腿", "周末菜"],
  }),
  extraDish({
    id: "creator-zhangliang-eggplant",
    name: "肉末茄子煲",
    source: "抖音",
    creator: "麻辣德子",
    creatorNote: "下饭家常和快速教程路线，适合想迅速决定今晚做什么。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 25,
    ingredients: [["茄子", "2根"], ["猪肉末", "150g"], ["蒜", "4瓣"]],
    steps: ["茄子切条煎软。", "炒香肉末和蒜末，加入调味汁。", "倒入茄子焖几分钟，收汁出锅。"],
    reason: "很适合米饭，做法也比馆子里的油炸版轻一些。",
    tags: ["下饭菜", "茄子", "快手"],
  }),
  extraDish({
    id: "creator-zhangliang-pepper-beef",
    name: "小炒黄牛肉",
    source: "抖音",
    creator: "麻辣德子",
    creatorNote: "下饭家常和快速教程路线，适合想迅速决定今晚做什么。",
    taste: "辣",
    difficulty: "中等",
    cookTime: 18,
    ingredients: [["牛肉", "250g"], ["小米椒", "4个"], ["香菜", "1把"]],
    steps: ["牛肉切薄片抓匀腌制。", "热锅快炒牛肉至变色。", "加入辣椒和香菜快速翻匀出锅。"],
    reason: "用时短但味道有冲击力，适合需要一道下饭硬菜的晚上。",
    tags: ["湘味", "牛肉", "快炒"],
  }),
  extraDish({
    id: "creator-james-three-cup",
    name: "台式三杯鸡",
    source: "B站",
    creator: "詹姆士的厨房",
    creatorNote: "偏家庭复刻和多菜系路线，适合在家探索不同地区的味道。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 35,
    ingredients: [["鸡腿肉", "400g"], ["九层塔", "1把"], ["姜", "8片"]],
    steps: ["鸡腿肉切块煎香。", "加入姜片、麻油、生抽和米酒焖煮。", "收汁后放九层塔快速翻匀。"],
    reason: "香气很特别，适合把普通鸡腿做出明显区别。",
    tags: ["台式", "鸡腿肉", "换口味"],
  }),
  extraDish({
    id: "creator-james-luroufan",
    name: "台式卤肉饭",
    source: "B站",
    creator: "詹姆士的厨房",
    creatorNote: "偏家庭复刻和多菜系路线，适合在家探索不同地区的味道。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 60,
    ingredients: [["五花肉", "400g"], ["香菇", "5朵"], ["米饭", "2碗"]],
    steps: ["五花肉切丁煸出油脂。", "加入香菇、红葱酥和调味料。", "加水慢卤，浇在米饭上。"],
    reason: "一次做一锅，之后加热就能快速吃上饭。",
    tags: ["台式", "盖饭", "备餐"],
  }),
  extraDish({
    id: "creator-foodranger-potato-beef",
    name: "土豆牛肉盖饭",
    source: "B站",
    creator: "食贫道",
    creatorNote: "饮食观察和地域风味路线，适合从各地吃法里找家常复刻灵感。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 40,
    ingredients: [["牛肉", "300g"], ["土豆", "2个"], ["洋葱", "半个"]],
    steps: ["牛肉切块煎香。", "加入洋葱和土豆翻炒。", "加水炖软收汁，盖在米饭上。"],
    reason: "味道朴素但很抗饿，适合忙碌日子的主食型晚餐。",
    tags: ["盖饭", "牛肉", "家常"],
  }),
  extraDish({
    id: "creator-foodranger-spicy-noodle",
    name: "酸辣肉臊拌面",
    source: "B站",
    creator: "食贫道",
    creatorNote: "饮食观察和地域风味路线，适合从各地吃法里找家常复刻灵感。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 22,
    ingredients: [["面条", "2份"], ["猪肉末", "150g"], ["醋", "2勺"]],
    steps: ["猪肉末炒香，加生抽和辣椒调味。", "面条煮熟沥干。", "加入肉臊、醋和葱花拌匀。"],
    reason: "面条路线能打破连续吃米饭的单调，做起来也很快。",
    tags: ["面食", "快手", "酸辣"],
  }),
  extraDish({
    id: "creator-wanggang-boiled-pork",
    name: "水煮肉片",
    source: "B站",
    creator: "美食作家王刚R",
    creatorNote: "硬核中餐教程型 UP，适合想把一道家常菜做扎实的时候看。",
    taste: "辣",
    difficulty: "中等",
    cookTime: 35,
    ingredients: [["里脊肉", "300g"], ["豆芽", "200g"], ["干辣椒", "1把"]],
    steps: ["里脊切片上浆，豆芽焯熟垫底。", "煮香豆瓣酱和高汤，下肉片滑熟。", "撒辣椒花椒，淋热油激香。"],
    reason: "适合周末做一顿痛快的辣味硬菜，也能练上浆和火候。",
    tags: ["川味", "硬菜", "下饭"],
  }),
  extraDish({
    id: "creator-laofangu-lion-head",
    name: "红烧狮子头",
    source: "B站",
    creator: "老饭骨",
    creatorNote: "老师傅讲细节的中餐频道，适合想把调味比例做稳定的人。",
    taste: "咸",
    difficulty: "困难",
    cookTime: 75,
    ingredients: [["猪肉馅", "500g"], ["马蹄", "6个"], ["青菜", "1把"]],
    steps: ["肉馅加入马蹄碎和调味料搅打上劲。", "团成丸子煎至表面定型。", "加高汤慢炖，最后配青菜收汁。"],
    reason: "步骤多一点，但很适合周末认真做一道传统菜。",
    tags: ["传统菜", "周末菜", "肉丸"],
  }),
  extraDish({
    id: "creator-mianyang-kimchi-pot",
    name: "泡菜肥牛锅",
    source: "B站",
    creator: "绵羊料理",
    creatorNote: "创意和实用感兼具，适合想把普通食材做得更有期待感。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 22,
    ingredients: [["肥牛卷", "250g"], ["泡菜", "200g"], ["豆腐", "1块"]],
    steps: ["泡菜炒香后加水煮开。", "加入豆腐和金针菇煮几分钟。", "最后下肥牛卷，变色后关火。"],
    reason: "天气凉时很舒服，一锅里还有肉、菜和汤。",
    tags: ["一锅菜", "韩式", "肥牛"],
  }),
  extraDish({
    id: "creator-panlaolao-meatball-soup",
    name: "冬瓜丸子汤",
    source: "小红书",
    creator: "潘姥姥",
    creatorNote: "乡间家常和治愈感强，适合想吃朴素热乎炖菜的时候。",
    taste: "清淡",
    difficulty: "简单",
    cookTime: 35,
    ingredients: [["冬瓜", "400g"], ["猪肉馅", "250g"], ["姜", "3片"]],
    steps: ["猪肉馅加调味料搅打上劲。", "冬瓜切片煮至半透明。", "挤入丸子煮熟，撒葱花调味。"],
    reason: "清爽但有肉香，适合一周里安排一道轻负担汤菜。",
    tags: ["汤菜", "清淡", "家常"],
  }),
  extraDish({
    id: "creator-xiashu-pepper-egg",
    name: "青椒炒蛋",
    source: "小红书",
    creator: "夏叔厨房",
    creatorNote: "主厨经验型内容，适合想学接地气但有章法的中餐。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 12,
    ingredients: [["青椒", "3个"], ["鸡蛋", "4个"], ["蒜", "2瓣"]],
    steps: ["青椒拍裂切块，鸡蛋打散。", "鸡蛋炒到蓬松盛出。", "青椒炒香后倒回鸡蛋调味。"],
    reason: "十二分钟就能上桌，是灵感池里需要保留的应急选项。",
    tags: ["快手", "鸡蛋", "应急菜"],
  }),
);
