import type { TrendingDish } from "./types";

export const TRENDING_DISHES: TrendingDish[] = [
  {
    id: "creator-wanggang-huiguorou",
    name: "家常版回锅肉",
    source: "B站",
    creator: "美食作家王刚R",
    creatorNote: "硬核中餐教程型 UP，适合想把一道家常菜做扎实的时候看。",
    taste: "辣",
    difficulty: "中等",
    cookTime: 28,
    ingredients: [
      { name: "五花肉", amount: "300g" },
      { name: "青蒜", amount: "4根" },
      { name: "郫县豆瓣酱", amount: "1勺" },
      { name: "甜面酱", amount: "半勺" },
    ],
    steps: ["五花肉冷水下锅煮至断生，放凉切薄片。", "小火煸出肉片油脂，加入豆瓣酱炒出红油。", "下青蒜和甜面酱快速翻炒，补少许生抽出锅。"],
    reason: "王刚系菜谱更偏基础功和锅气，回锅肉是适合练火候的下饭硬菜。",
    tags: ["B站UP主", "川味", "下饭菜"],
    searchKeyword: "美食作家王刚R 回锅肉",
  },
  {
    id: "creator-laofangu-yuxiangrousi",
    name: "鱼香肉丝",
    source: "B站",
    creator: "老饭骨",
    creatorNote: "老师傅讲细节的中餐频道，适合想把调味比例做稳定的人。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 26,
    ingredients: [
      { name: "里脊肉", amount: "250g" },
      { name: "木耳", amount: "1把" },
      { name: "胡萝卜", amount: "半根" },
      { name: "泡椒", amount: "2勺" },
    ],
    steps: ["里脊切丝上浆，配菜切丝。", "调鱼香汁：醋、糖、生抽、淀粉和清水混合。", "肉丝滑散后炒香泡椒，加入配菜和鱼香汁收浓。"],
    reason: "鱼香味最怕比例飘，老饭骨类教程适合对照学习调味逻辑。",
    tags: ["B站UP主", "经典家常", "调味练习"],
    searchKeyword: "老饭骨 鱼香肉丝",
  },
  {
    id: "creator-manshiman-yu-tomato-beef",
    name: "番茄牛腩",
    source: "B站",
    creator: "曼食慢语",
    creatorNote: "步骤清楚、画面舒服，适合周末备餐和慢炖菜。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 70,
    ingredients: [
      { name: "牛腩", amount: "500g" },
      { name: "番茄", amount: "4个" },
      { name: "土豆", amount: "1个" },
      { name: "洋葱", amount: "半个" },
    ],
    steps: ["牛腩焯水，番茄去皮切块。", "洋葱和番茄炒出浓汁，加入牛腩和热水炖煮。", "最后加入土豆炖软，盐和黑胡椒调味。"],
    reason: "适合一次多做，第二天拌饭或带饭都很稳。",
    tags: ["B站UP主", "炖菜", "备餐"],
    searchKeyword: "曼食慢语 番茄牛腩",
  },
  {
    id: "creator-mianyang-teriyaki-chicken",
    name: "照烧鸡腿饭",
    source: "B站",
    creator: "绵羊料理",
    creatorNote: "创意和实用感兼具，适合想把普通食材做得更有期待感。",
    taste: "甜",
    difficulty: "简单",
    cookTime: 24,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "米饭", amount: "2碗" },
      { name: "生抽", amount: "2勺" },
      { name: "蜂蜜", amount: "1勺" },
    ],
    steps: ["鸡腿去骨，用少许盐和黑胡椒腌制。", "鸡皮面先煎出油脂，翻面煎熟。", "倒入照烧汁收浓，切块盖在米饭上。"],
    reason: "鸡腿饭是视频平台常青题材，食材好买、成品反馈强。",
    tags: ["B站UP主", "盖饭", "一人食"],
    searchKeyword: "绵羊料理 照烧鸡腿饭",
  },
  {
    id: "creator-daoyueshe-market-stir-fry",
    name: "菜市场小炒肉",
    source: "B站",
    creator: "盗月社食遇记",
    creatorNote: "偏烟火气和市井灵感，适合不知道买什么时去找菜市场思路。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 20,
    ingredients: [
      { name: "梅花肉", amount: "250g" },
      { name: "螺丝椒", amount: "4个" },
      { name: "蒜", amount: "3瓣" },
      { name: "豆豉", amount: "1勺" },
    ],
    steps: ["肉切薄片，螺丝椒拍裂切段。", "热锅煸香肉片和蒜，加入豆豉。", "下辣椒大火炒出虎皮感，用生抽和盐调味。"],
    reason: "这类内容更像“今天去市场看到什么就做什么”，适合解决选择困难。",
    tags: ["B站UP主", "菜市场", "快手下饭"],
    searchKeyword: "盗月社食遇记 菜市场 小炒肉",
  },
  {
    id: "creator-gaoyuyu-sprite-noodle",
    name: "雪碧拌面",
    source: "小红书",
    creator: "高芋芋",
    creatorNote: "小红书爆款美食博主路线，适合想要低门槛、强记忆点的快手菜。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 15,
    ingredients: [
      { name: "面条", amount: "2份" },
      { name: "黄瓜", amount: "半根" },
      { name: "雪碧", amount: "3勺" },
      { name: "芝麻酱", amount: "1勺" },
    ],
    steps: ["面条煮熟过凉水，黄瓜切丝。", "用芝麻酱、生抽、醋、辣椒油和少量雪碧调汁。", "面条沥干后拌匀，按口味补蒜末和香菜。"],
    reason: "适合没胃口或不想开大火的时候，平台传播感很强。",
    tags: ["小红书博主", "快手面", "爆款感"],
    searchKeyword: "高芋芋 雪碧拌面",
  },
  {
    id: "creator-xiaoyugugu-cheese-chicken",
    name: "芝士鸡腿",
    source: "小红书",
    creator: "小宇菇菇",
    creatorNote: "高颜值还原和治愈系美食内容，适合周末做一顿有仪式感的。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 35,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "芝士片", amount: "2片" },
      { name: "面包糠", amount: "适量" },
      { name: "鸡蛋", amount: "1个" },
    ],
    steps: ["鸡腿去骨展开，盐和黑胡椒腌制。", "夹入芝士后裹蛋液和面包糠。", "空气炸锅或烤箱烤至表面金黄。"],
    reason: "比普通鸡腿更有新鲜感，适合想吃点开心的晚餐。",
    tags: ["小红书博主", "空气炸锅", "高颜值"],
    searchKeyword: "小宇菇菇 芝士鸡腿",
  },
  {
    id: "creator-pupujiji-bento",
    name: "照烧鸡腿便当",
    source: "小红书",
    creator: "噗噗叽叽",
    creatorNote: "便当和家常菜氛围强，适合把晚餐顺手变成第二天午餐。",
    taste: "甜",
    difficulty: "简单",
    cookTime: 28,
    ingredients: [
      { name: "鸡腿", amount: "2只" },
      { name: "西兰花", amount: "半颗" },
      { name: "胡萝卜", amount: "半根" },
      { name: "米饭", amount: "2碗" },
    ],
    steps: ["鸡腿去骨煎熟，倒入照烧汁收汁。", "西兰花和胡萝卜焯水调味。", "米饭装盒，铺上鸡腿和配菜。"],
    reason: "适合工作日，做一顿能解决晚餐和带饭。",
    tags: ["小红书博主", "便当", "带饭"],
    searchKeyword: "噗噗叽叽 照烧鸡腿便当",
  },
  {
    id: "creator-xiashu-tofu",
    name: "葱烧豆腐",
    source: "小红书",
    creator: "夏叔厨房",
    creatorNote: "主厨经验型内容，适合想学接地气但有章法的中餐。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 18,
    ingredients: [
      { name: "老豆腐", amount: "1块" },
      { name: "大葱", amount: "1根" },
      { name: "生抽", amount: "2勺" },
      { name: "蚝油", amount: "1勺" },
    ],
    steps: ["豆腐切厚片煎到两面金黄。", "大葱煸香，加入生抽、蚝油和少许水。", "放回豆腐小火烧入味，收汁出锅。"],
    reason: "便宜、下饭、蛋白质够，是一周菜单里很好补位的素菜。",
    tags: ["小红书博主", "豆腐", "省钱菜"],
    searchKeyword: "夏叔厨房 葱烧豆腐",
  },
  {
    id: "creator-panlaolao-chicken-potato",
    name: "土豆烧鸡",
    source: "小红书",
    creator: "潘姥姥",
    creatorNote: "乡间家常和治愈感强，适合想吃朴素热乎炖菜的时候。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 45,
    ingredients: [
      { name: "鸡块", amount: "500g" },
      { name: "土豆", amount: "2个" },
      { name: "姜", amount: "4片" },
      { name: "八角", amount: "1个" },
    ],
    steps: ["鸡块焯水，土豆切滚刀块。", "炒香姜片和鸡块，加入生抽、老抽和热水。", "炖至鸡肉入味后下土豆，收浓汤汁。"],
    reason: "热乎、有汤汁、很适合米饭，是不容易踩雷的家常炖菜。",
    tags: ["小红书博主", "炖菜", "家常"],
    searchKeyword: "潘姥姥 土豆烧鸡",
  },
  {
    id: "creator-wanggang-kungpao-chicken",
    name: "宫保鸡丁",
    source: "B站",
    creator: "美食作家王刚R",
    creatorNote: "硬核中餐教程型 UP，适合想把一道家常菜做扎实的时候看。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 24,
    ingredients: [
      { name: "鸡腿肉", amount: "300g" },
      { name: "花生米", amount: "1把" },
      { name: "干辣椒", amount: "6个" },
      { name: "大葱", amount: "1根" },
    ],
    steps: ["鸡腿肉切丁上浆，调好糖醋宫保汁。", "热锅滑散鸡丁，炒香干辣椒和葱段。", "倒入鸡丁、花生米和料汁，大火翻匀收亮。"],
    reason: "同样是王刚路线，但比回锅肉更考验调汁，适合想练经典川菜的时候。",
    tags: ["B站UP主", "川菜", "鸡腿肉"],
    searchKeyword: "美食作家王刚R 宫保鸡丁",
  },
  {
    id: "creator-laofangu-braised-pork",
    name: "红烧肉",
    source: "B站",
    creator: "老饭骨",
    creatorNote: "老师傅讲细节的中餐频道，适合想把调味比例做稳定的人。",
    taste: "咸",
    difficulty: "中等",
    cookTime: 65,
    ingredients: [
      { name: "五花肉", amount: "500g" },
      { name: "冰糖", amount: "1小把" },
      { name: "姜", amount: "5片" },
      { name: "生抽", amount: "2勺" },
    ],
    steps: ["五花肉切块焯水，沥干备用。", "小火炒糖色，下肉块翻匀。", "加热水和调味料慢炖，最后大火收汁。"],
    reason: "适合周末慢慢做的一道菜，喜欢老饭骨后会更多推荐这类传统中餐硬菜。",
    tags: ["B站UP主", "硬菜", "周末菜"],
    searchKeyword: "老饭骨 红烧肉",
  },
  {
    id: "creator-manshiman-curry-chicken",
    name: "日式咖喱鸡饭",
    source: "B站",
    creator: "曼食慢语",
    creatorNote: "步骤清楚、画面舒服，适合周末备餐和慢炖菜。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 35,
    ingredients: [
      { name: "鸡腿肉", amount: "300g" },
      { name: "土豆", amount: "1个" },
      { name: "胡萝卜", amount: "1根" },
      { name: "咖喱块", amount: "2块" },
    ],
    steps: ["鸡腿肉、土豆和胡萝卜切块。", "鸡肉煎香后加入蔬菜翻炒。", "加水煮软，放入咖喱块煮到浓稠。"],
    reason: "一锅解决主菜和拌饭，适合做成两顿饭。",
    tags: ["B站UP主", "盖饭", "备餐"],
    searchKeyword: "曼食慢语 日式咖喱鸡饭",
  },
  {
    id: "creator-mianyang-garlic-shrimp",
    name: "蒜香黄油虾",
    source: "B站",
    creator: "绵羊料理",
    creatorNote: "创意和实用感兼具，适合想把普通食材做得更有期待感。",
    taste: "鲜",
    difficulty: "简单",
    cookTime: 18,
    ingredients: [
      { name: "虾", amount: "300g" },
      { name: "蒜", amount: "1头" },
      { name: "黄油", amount: "15g" },
      { name: "黑胡椒", amount: "适量" },
    ],
    steps: ["虾开背去虾线，蒜切末。", "黄油融化后炒香蒜末。", "下虾煎熟，黑胡椒和盐调味。"],
    reason: "步骤短但成品有餐厅感，适合想换口味时刷新出来。",
    tags: ["B站UP主", "快手", "海鲜"],
    searchKeyword: "绵羊料理 蒜香黄油虾",
  },
  {
    id: "creator-gaoyuyu-sour-hot-mix",
    name: "酸辣凉拌宽粉",
    source: "小红书",
    creator: "高芋芋",
    creatorNote: "小红书爆款美食博主路线，适合想要低门槛、强记忆点的快手菜。",
    taste: "辣",
    difficulty: "简单",
    cookTime: 16,
    ingredients: [
      { name: "宽粉", amount: "1把" },
      { name: "黄瓜", amount: "半根" },
      { name: "花生碎", amount: "1勺" },
      { name: "辣椒油", amount: "1勺" },
    ],
    steps: ["宽粉煮熟过凉水，黄瓜切丝。", "生抽、醋、辣椒油、蒜末调成酸辣汁。", "把宽粉和配菜拌匀，撒花生碎。"],
    reason: "和雪碧拌面同属低门槛爆款路线，适合不想认真开火的晚上。",
    tags: ["小红书博主", "凉拌", "快手"],
    searchKeyword: "高芋芋 酸辣宽粉",
  },
  {
    id: "creator-pupujiji-omelet-rice",
    name: "蛋包饭",
    source: "小红书",
    creator: "噗噗叽叽",
    creatorNote: "便当和家常菜氛围强，适合把晚餐顺手变成第二天午餐。",
    taste: "酸甜",
    difficulty: "中等",
    cookTime: 25,
    ingredients: [
      { name: "米饭", amount: "2碗" },
      { name: "鸡蛋", amount: "3个" },
      { name: "番茄酱", amount: "2勺" },
      { name: "火腿", amount: "1根" },
    ],
    steps: ["米饭加火腿和番茄酱炒匀。", "鸡蛋打散，小火摊成蛋皮。", "蛋皮包住炒饭，表面挤番茄酱。"],
    reason: "视觉反馈强，适合想做一顿轻松但不敷衍的晚餐。",
    tags: ["小红书博主", "便当", "米饭"],
    searchKeyword: "噗噗叽叽 蛋包饭",
  },
  {
    id: "creator-xiashu-eggplant",
    name: "酱烧茄子",
    source: "小红书",
    creator: "夏叔厨房",
    creatorNote: "主厨经验型内容，适合想学接地气但有章法的中餐。",
    taste: "咸",
    difficulty: "简单",
    cookTime: 22,
    ingredients: [
      { name: "茄子", amount: "2根" },
      { name: "蒜", amount: "4瓣" },
      { name: "黄豆酱", amount: "1勺" },
      { name: "青椒", amount: "1个" },
    ],
    steps: ["茄子切条，用少许盐抓一下出水。", "锅中煎软茄子，炒香蒜末和黄豆酱。", "加入青椒和茄子翻匀，少量水焖入味。"],
    reason: "素菜也能很下饭，适合喜欢夏叔厨房后补充传统家常菜。",
    tags: ["小红书博主", "素菜", "下饭"],
    searchKeyword: "夏叔厨房 酱烧茄子",
  },
  {
    id: "creator-panlaolao-ribs-corn",
    name: "玉米排骨汤",
    source: "小红书",
    creator: "潘姥姥",
    creatorNote: "乡间家常和治愈感强，适合想吃朴素热乎炖菜的时候。",
    taste: "清淡",
    difficulty: "简单",
    cookTime: 55,
    ingredients: [
      { name: "排骨", amount: "500g" },
      { name: "玉米", amount: "1根" },
      { name: "胡萝卜", amount: "1根" },
      { name: "姜", amount: "4片" },
    ],
    steps: ["排骨焯水洗净。", "排骨、姜片和清水先炖35分钟。", "加入玉米和胡萝卜继续炖，最后加盐。"],
    reason: "喜欢潘姥姥后，更适合推荐这种热乎、朴素、家常的汤菜。",
    tags: ["小红书博主", "汤菜", "清淡"],
    searchKeyword: "潘姥姥 玉米排骨汤",
  },
];
